export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
}

export enum AdminPermission {
  // Companies
  VIEW_COMPANIES = 'VIEW_COMPANIES',
  CREATE_COMPANIES = 'CREATE_COMPANIES',
  UPDATE_COMPANIES = 'UPDATE_COMPANIES',
  DELETE_COMPANIES = 'DELETE_COMPANIES',

  // Departments
  VIEW_DEPARTMENTS = 'VIEW_DEPARTMENTS',
  CREATE_DEPARTMENTS = 'CREATE_DEPARTMENTS',
  UPDATE_DEPARTMENTS = 'UPDATE_DEPARTMENTS',
  DELETE_DEPARTMENTS = 'DELETE_DEPARTMENTS',

  // Users
  VIEW_USERS = 'VIEW_USERS',
  CREATE_USERS = 'CREATE_USERS',
  UPDATE_USERS = 'UPDATE_USERS',
  DELETE_USERS = 'DELETE_USERS',

  // Items/Assets
  VIEW_ITEMS = 'VIEW_ITEMS',
  CREATE_ITEMS = 'CREATE_ITEMS',
  UPDATE_ITEMS = 'UPDATE_ITEMS',
  DELETE_ITEMS = 'DELETE_ITEMS',
  ASSIGN_ITEMS = 'ASSIGN_ITEMS',

  // Item Status
  MANAGE_REPAIRS = 'MANAGE_REPAIRS',
  MANAGE_DISPOSALS = 'MANAGE_DISPOSALS',

  // Warehouse
  VIEW_WAREHOUSE = 'VIEW_WAREHOUSE',

  // Categories
  VIEW_CATEGORIES = 'VIEW_CATEGORIES',
  CREATE_CATEGORIES = 'CREATE_CATEGORIES',
  UPDATE_CATEGORIES = 'UPDATE_CATEGORIES',
  DELETE_CATEGORIES = 'DELETE_CATEGORIES',
  MANAGE_CATEGORIES = 'MANAGE_CATEGORIES', // Legacy compatibility

  // Licenses
  VIEW_LICENSES = 'VIEW_LICENSES',
  CREATE_LICENSES = 'CREATE_LICENSES',
  UPDATE_LICENSES = 'UPDATE_LICENSES',
  DELETE_LICENSES = 'DELETE_LICENSES',


  // Reports & Analytics
  VIEW_REPORTS = 'VIEW_REPORTS',
  EXPORT_DATA = 'EXPORT_DATA',

  // Barcode & Labels
  GENERATE_BARCODES = 'GENERATE_BARCODES',

  // Audit
  VIEW_AUDIT_LOGS = 'VIEW_AUDIT_LOGS',

  // System Settings
  VIEW_SETTINGS = 'VIEW_SETTINGS',
  UPDATE_SETTINGS = 'UPDATE_SETTINGS',
}

export enum ItemStatus {
  WAREHOUSE = 'WAREHOUSE',
  IN_USE = 'IN_USE',
  IN_REPAIR = 'IN_REPAIR',
  SENT_TO_REPAIR = 'SENT_TO_REPAIR',
  DISPOSED = 'DISPOSED',
  LOST = 'LOST',
  IN_TRANSIT = 'IN_TRANSIT',
}

export enum ItemCondition {
  NEW = 'NEW',
  GOOD = 'GOOD',
  FAIR = 'FAIR',
  DAMAGED = 'DAMAGED',
  IRREPARABLE = 'IRREPARABLE',
}

export enum ItemEventType {
  ITEM_ADDED = 'ITEM_ADDED',
  ITEM_EDITED = 'ITEM_EDITED',
  ASSIGNED_TO_DEPARTMENT = 'ASSIGNED_TO_DEPARTMENT',
  ASSIGNED_TO_PERSON = 'ASSIGNED_TO_PERSON',
  UNASSIGNED = 'UNASSIGNED',
  SENT_TO_REPAIR = 'SENT_TO_REPAIR',
  RETURNED_FROM_REPAIR = 'RETURNED_FROM_REPAIR',
  MARKED_WORKING = 'MARKED_WORKING',
  MARKED_NOT_WORKING = 'MARKED_NOT_WORKING',
  CONDITION_UPDATED = 'CONDITION_UPDATED',
  MOVED_TO_WAREHOUSE = 'MOVED_TO_WAREHOUSE',
  DISPOSAL_REQUESTED = 'DISPOSAL_REQUESTED',
  DISPOSAL_APPROVED = 'DISPOSAL_APPROVED',
  DISPOSED = 'DISPOSED',
  LOST_REPORTED = 'LOST_REPORTED',
  FOUND = 'FOUND',
  NOTES_UPDATED = 'NOTES_UPDATED',
  TRANSFERRED = 'TRANSFERRED',
}

export enum DisposalMethod {
  SCRAPPED = 'SCRAPPED',
  DONATED = 'DONATED',
  SOLD = 'SOLD',
  RECYCLED = 'RECYCLED',
}

export enum NotificationType {
  ITEM_ADDED = 'ITEM_ADDED',
  ITEM_ASSIGNED = 'ITEM_ASSIGNED',
  ITEM_SENT_TO_REPAIR = 'ITEM_SENT_TO_REPAIR',
  ITEM_RETURNED_FROM_REPAIR = 'ITEM_RETURNED_FROM_REPAIR',
  ITEM_DISPOSED = 'ITEM_DISPOSED',
  DISPOSAL_REQUESTED = 'DISPOSAL_REQUESTED',
  DISPOSAL_APPROVED = 'DISPOSAL_APPROVED',
  ITEM_LOST = 'ITEM_LOST',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  ACCOUNT_PERMISSIONS_UPDATED = 'ACCOUNT_PERMISSIONS_UPDATED',
  ACCOUNT_ROLE_UPDATED = 'ACCOUNT_ROLE_UPDATED',

  // License Notifications
  LICENSE_ADDED = 'LICENSE_ADDED',
  LICENSE_UPDATED = 'LICENSE_UPDATED',
  LICENSE_EXPIRING = 'LICENSE_EXPIRING',
  LICENSE_EXPIRED = 'LICENSE_EXPIRED',
  USER_UPDATED = 'USER_UPDATED',
  ITEM_WARRANTY_EXPIRING = 'ITEM_WARRANTY_EXPIRING',
  ITEM_WARRANTY_EXPIRED = 'ITEM_WARRANTY_EXPIRED',

  // Report Notifications
  REPORT_SCHEDULED = 'REPORT_SCHEDULED',
  REPORT_DISPATCHED = 'REPORT_DISPATCHED',
}
