import * as ExcelJS from 'exceljs';
import { Injectable } from '@nestjs/common';

@Injectable()
export class ExcelGenerator {
  async generateBuffer(data: any[], columns: any[], sheetName = 'Report', generatedByContext?: string): Promise<Buffer> {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'Inventory System';
    workbook.created = new Date();

    const sheet = workbook.addWorksheet(sheetName);

    // Set column keys and widths ONLY (no header here to avoid row 1 overwrite)
    sheet.columns = columns.map(col => ({
      key: col.key,
      width: col.width || 20,
    }));

    let rowNum = 1;
    sheet.getCell(`A${rowNum}`).value = 'Inventory system generated report';
    sheet.getCell(`A${rowNum}`).font = { bold: true, size: 14 };
    rowNum++;

    sheet.getCell(`A${rowNum++}`).value = `Generated on: ${new Date().toLocaleString()}`;
    
    if (generatedByContext) {
      sheet.getCell(`A${rowNum++}`).value = `Generated by: ${generatedByContext}`;
    }
    rowNum++; // blank row

    // Add headers manually
    const headerRow = sheet.getRow(rowNum);
    headerRow.values = columns.map(col => col.header);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF1677FF' }, // Ant Design Blue
    };

    // Freeze everything down to the newly added header row
    sheet.views = [{ state: 'frozen', xSplit: 0, ySplit: rowNum }];

    data.forEach(item => {
      sheet.addRow(columns.map(col => item[col.key]));
    });

    const buffer = await workbook.xlsx.writeBuffer();
    return Buffer.from(buffer);
  }
}
