export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  COMPANY_ADMIN = 'COMPANY_ADMIN',
  WAREHOUSE_ADMIN = 'WAREHOUSE_ADMIN',
  DEPT_ADMIN = 'DEPT_ADMIN',
  STAFF = 'STAFF',
  REPAIR_HANDLER = 'REPAIR_HANDLER',
}

export enum ItemStatus {
  WAREHOUSE = 'WAREHOUSE',
  DISTRIBUTED = 'DISTRIBUTED',
  ASSIGNED = 'ASSIGNED',
  IN_TRANSIT = 'IN_TRANSIT',
  IN_REPAIR = 'IN_REPAIR',
  RETURNED_FROM_REPAIR = 'RETURNED_FROM_REPAIR',
  DISPOSED = 'DISPOSED',
  LOST = 'LOST',
}

export enum ItemCondition {
  NEW = 'NEW',
  GOOD = 'GOOD',
  FAIR = 'FAIR',
  DAMAGED = 'DAMAGED',
  IRREPARABLE = 'IRREPARABLE',
}

export enum ItemEventType {
  RECEIVED = 'RECEIVED',
  BARCODE_GENERATED = 'BARCODE_GENERATED',
  DISTRIBUTED_TO_DEPT = 'DISTRIBUTED_TO_DEPT',
  DEPT_ACKNOWLEDGED = 'DEPT_ACKNOWLEDGED',
  ASSIGNED_TO_USER = 'ASSIGNED_TO_USER',
  USER_ACKNOWLEDGED = 'USER_ACKNOWLEDGED',
  FAULT_REPORTED = 'FAULT_REPORTED',
  REPAIR_REQUESTED = 'REPAIR_REQUESTED',
  PICKED_UP_FOR_REPAIR = 'PICKED_UP_FOR_REPAIR',
  REPAIR_IN_PROGRESS = 'REPAIR_IN_PROGRESS',
  REPAIR_COMPLETED = 'REPAIR_COMPLETED',
  RETURNED_FROM_REPAIR = 'RETURNED_FROM_REPAIR',
  REASSIGNED = 'REASSIGNED',
  TRANSFERRED_TO_DEPT = 'TRANSFERRED_TO_DEPT',
  RETURNED_TO_WAREHOUSE = 'RETURNED_TO_WAREHOUSE',
  DISPOSAL_REQUESTED = 'DISPOSAL_REQUESTED',
  DISPOSED = 'DISPOSED',
  LOST_REPORTED = 'LOST_REPORTED',
  FOUND = 'FOUND',
  CONDITION_UPDATED = 'CONDITION_UPDATED',
  NOTES_UPDATED = 'NOTES_UPDATED',
  IMPORTED = 'IMPORTED',
}

export enum PRStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  COMPANY_APPROVED = 'COMPANY_APPROVED',
  SUPER_ADMIN_REQUIRED = 'SUPER_ADMIN_REQUIRED',
  SUPER_APPROVED = 'SUPER_APPROVED',
  REJECTED = 'REJECTED',
  ORDERED = 'ORDERED',
  PARTIALLY_RECEIVED = 'PARTIALLY_RECEIVED',
  FULLY_RECEIVED = 'FULLY_RECEIVED',
  CLOSED = 'CLOSED',
}

export enum OrderStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  SHIPPED = 'SHIPPED',
  PARTIALLY_RECEIVED = 'PARTIALLY_RECEIVED',
  RECEIVED = 'RECEIVED',
  CANCELLED = 'CANCELLED',
}

export enum VendorType {
  SUPPLIER = 'SUPPLIER',
  REPAIR_SHOP = 'REPAIR_SHOP',
  BOTH = 'BOTH',
}

export enum Urgency {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum RepairStatus {
  REPORTED = 'REPORTED',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  HANDLER_ASSIGNED = 'HANDLER_ASSIGNED',
  AWAITING_PICKUP = 'AWAITING_PICKUP',
  PICKED_UP = 'PICKED_UP',
  RECEIVED_AT_SHOP = 'RECEIVED_AT_SHOP',
  DIAGNOSED = 'DIAGNOSED',
  AWAITING_PARTS = 'AWAITING_PARTS',
  IN_REPAIR = 'IN_REPAIR',
  QUALITY_CHECK = 'QUALITY_CHECK',
  REPAIRED = 'REPAIRED',
  IRREPARABLE = 'IRREPARABLE',
  RETURNING = 'RETURNING',
  RETURNED = 'RETURNED',
}

export enum RepairOutcome {
  REPAIRED = 'REPAIRED',
  IRREPARABLE = 'IRREPARABLE',
  REPLACED = 'REPLACED',
}

export enum DisposalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  DISPOSED = 'DISPOSED',
}

export enum DisposalMethod {
  SCRAPPED = 'SCRAPPED',
  DONATED = 'DONATED',
  SOLD = 'SOLD',
  RETURNED_TO_VENDOR = 'RETURNED_TO_VENDOR',
}

export enum DisposalReason {
  IRREPARABLE = 'IRREPARABLE',
  END_OF_LIFE = 'END_OF_LIFE',
  LOST = 'LOST',
  OBSOLETE = 'OBSOLETE',
  DAMAGED_BEYOND_USE = 'DAMAGED_BEYOND_USE',
}

export enum TransferStatus {
  INITIATED = 'INITIATED',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  CANCELLED = 'CANCELLED',
}

export enum TransferType {
  WAREHOUSE_TO_DEPT = 'WAREHOUSE_TO_DEPT',
  DEPT_TO_DEPT = 'DEPT_TO_DEPT',
  DEPT_TO_REPAIR = 'DEPT_TO_REPAIR',
  REPAIR_TO_WAREHOUSE = 'REPAIR_TO_WAREHOUSE',
  DEPT_TO_WAREHOUSE = 'DEPT_TO_WAREHOUSE',
  WAREHOUSE_TO_REPAIR = 'WAREHOUSE_TO_REPAIR',
}
