export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
}

export enum AdminPermission {
  // Company & Department Management
  MANAGE_COMPANIES = 'MANAGE_COMPANIES',
  MANAGE_DEPARTMENTS = 'MANAGE_DEPARTMENTS',

  // User Management
  MANAGE_USERS = 'MANAGE_USERS',

  // Item Management
  ADD_ITEMS = 'ADD_ITEMS',
  EDIT_ITEMS = 'EDIT_ITEMS',
  DELETE_ITEMS = 'DELETE_ITEMS',
  ASSIGN_ITEMS = 'ASSIGN_ITEMS',

  // Item Status
  MANAGE_REPAIRS = 'MANAGE_REPAIRS',
  MANAGE_DISPOSALS = 'MANAGE_DISPOSALS',

  // Warehouse
  VIEW_WAREHOUSE = 'VIEW_WAREHOUSE',

  // Categories
  MANAGE_CATEGORIES = 'MANAGE_CATEGORIES',

  // Reports & Analytics
  VIEW_REPORTS = 'VIEW_REPORTS',
  EXPORT_DATA = 'EXPORT_DATA',

  // Barcode & Labels
  GENERATE_BARCODES = 'GENERATE_BARCODES',

  // Audit
  VIEW_AUDIT_LOGS = 'VIEW_AUDIT_LOGS',
}

export enum ItemStatus {
  WAREHOUSE = 'WAREHOUSE',
  IN_USE = 'IN_USE',
  IN_REPAIR = 'IN_REPAIR',
  SENT_TO_REPAIR = 'SENT_TO_REPAIR',
  DISPOSED = 'DISPOSED',
  LOST = 'LOST',
  IN_TRANSIT = 'IN_TRANSIT',
}

export enum ItemCondition {
  NEW = 'NEW',
  GOOD = 'GOOD',
  FAIR = 'FAIR',
  DAMAGED = 'DAMAGED',
  IRREPARABLE = 'IRREPARABLE',
}

export enum ItemEventType {
  ITEM_ADDED = 'ITEM_ADDED',
  ITEM_EDITED = 'ITEM_EDITED',
  ASSIGNED_TO_DEPARTMENT = 'ASSIGNED_TO_DEPARTMENT',
  ASSIGNED_TO_PERSON = 'ASSIGNED_TO_PERSON',
  UNASSIGNED = 'UNASSIGNED',
  SENT_TO_REPAIR = 'SENT_TO_REPAIR',
  RETURNED_FROM_REPAIR = 'RETURNED_FROM_REPAIR',
  MARKED_WORKING = 'MARKED_WORKING',
  MARKED_NOT_WORKING = 'MARKED_NOT_WORKING',
  CONDITION_UPDATED = 'CONDITION_UPDATED',
  MOVED_TO_WAREHOUSE = 'MOVED_TO_WAREHOUSE',
  DISPOSAL_REQUESTED = 'DISPOSAL_REQUESTED',
  DISPOSAL_APPROVED = 'DISPOSAL_APPROVED',
  DISPOSED = 'DISPOSED',
  LOST_REPORTED = 'LOST_REPORTED',
  FOUND = 'FOUND',
  NOTES_UPDATED = 'NOTES_UPDATED',
  TRANSFERRED = 'TRANSFERRED',
}

export enum DisposalMethod {
  SCRAPPED = 'SCRAPPED',
  DONATED = 'DONATED',
  SOLD = 'SOLD',
  RECYCLED = 'RECYCLED',
}

export enum NotificationType {
  ITEM_ADDED = 'ITEM_ADDED',
  ITEM_ASSIGNED = 'ITEM_ASSIGNED',
  ITEM_SENT_TO_REPAIR = 'ITEM_SENT_TO_REPAIR',
  ITEM_RETURNED_FROM_REPAIR = 'ITEM_RETURNED_FROM_REPAIR',
  ITEM_DISPOSED = 'ITEM_DISPOSED',
  DISPOSAL_REQUESTED = 'DISPOSAL_REQUESTED',
  DISPOSAL_APPROVED = 'DISPOSAL_APPROVED',
  ITEM_LOST = 'ITEM_LOST',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
}
